name: Agentic Infrastructure Management

on:
  push:
    paths:
      - 'inframate.md'
      - '.github/workflows/agentic_infra_management.yml'
  pull_request:
    paths:
      - 'inframate.md'
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Target repository to analyze'
        required: true
        default: '.'
      target_branch:
        description: 'Branch to analyze'
        required: true
        default: 'main'
      action:
        description: 'Action to perform (analyze, optimize, secure, visualize, auto)'
        required: true
        default: 'analyze'
      autonomous_mode:
        description: 'Run in fully autonomous mode'
        required: true
        default: 'false'
        type: boolean

jobs:
  agentic-infra-management:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Inframate
        uses: actions/checkout@v4
        with:
          path: inframate
          
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.target_repo }}
          ref: ${{ github.event.inputs.target_branch }}
          path: target_repo
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.0'
          
      - name: Install dependencies
        run: |
          # Install system dependencies
          sudo apt-get update
          sudo apt-get install -y graphviz
          
          # Install Python dependencies
          python -m pip install --upgrade pip
          pip install -r inframate/scripts/visualization/requirements.txt
          pip install google-generativeai langchain requests
          
      - name: Copy visualization scripts
        run: |
          mkdir -p scripts
          cp -r inframate/scripts/visualization scripts/
      
      - name: Run agentic workflow with AI error handling
        id: run-workflow
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ACTION: ${{ github.event.inputs.action }}
          AUTONOMOUS_MODE: ${{ github.event.inputs.autonomous_mode }}
        run: |
          # Run the workflow with error handling
          python inframate/scripts/agentic_error_workflow.py \
            --repo-path target_repo \
            --action $ACTION \
            --autonomous $AUTONOMOUS_MODE \
            --output analysis_results.json
          
          # Check if we have errors with AI solutions
          if jq -e '.success == false' analysis_results.json > /dev/null; then
            echo "::warning::Workflow encountered errors - Gemini AI has provided solutions"
            
            # Extract AI solution as markdown
            jq -r '.error.ai_solution | 
              "## 🤖 AI Analysis of the Error\n\n" +
              "### Root Cause\n" + 
              (.root_cause // "Unknown") + "\n\n" +
              "### Solution\n" + 
              (.solution // "No solution available") + "\n\n" +
              "### Prevention\n" + 
              (.prevention // "No prevention tips available")' \
              analysis_results.json > ai_solution.md
            
            echo "AI_SOLUTION_AVAILABLE=true" >> $GITHUB_ENV
            echo "has_errors=true" >> $GITHUB_OUTPUT
          else 
            echo "::notice::Workflow completed successfully with no errors"
            echo "has_errors=false" >> $GITHUB_OUTPUT
          fi
          
          # Display summary of results
          echo "✅ Analysis completed! Summary of findings:"
          jq -r '.analysis.resource_counts | length | "Found \(.) unique AWS resource types"' analysis_results.json 2>/dev/null || echo "No resource count available"
          jq -r '.optimization.recommendations | length | "\(.) optimization recommendations found"' analysis_results.json 2>/dev/null || echo "No optimization recommendations available"
          
      - name: Create Issue with AI Error Analysis
        if: steps.run-workflow.outputs.has_errors == 'true'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "🚨 Inframate Error with AI Solution"
          content-filepath: ai_solution.md
          labels: error, ai-solution
          
      - name: Create Pull Request with findings
        if: github.event.inputs.action != 'analyze'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: target_repo
          commit-message: "🤖 Inframate Agent: Infrastructure improvements"
          title: "🤖 Inframate Agent: ${{ github.event.inputs.action }} recommendations"
          body-path: analysis_results.json
          branch: "inframate/agent-recommendations"
          base: ${{ github.event.inputs.target_branch }}
          
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: inframate-analysis
          path: |
            analysis_results.json
            ai_solution.md
            target_repo/visualizations/
          retention-days: 7 