name: Inframate Analysis

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Target repository to analyze'
        required: true
        default: '.'
      target_branch:
        description: 'Target branch to create PR against'
        required: true
        default: 'main'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Inframate
        uses: actions/checkout@v4
        with:
          path: inframate

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.target_repo }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: target_repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'inframate/setup.py'

      - name: Install Inframate
        run: |
          python -m pip install --upgrade pip
          cd inframate
          pip install -e .

      - name: Run Inframate
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          cd target_repo
          inframate .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Inframate: Generated Terraform files"
          title: "Inframate: Infrastructure Recommendations and Terraform Files"
          body: |
            This PR contains infrastructure recommendations and Terraform files generated by Inframate.
            
            ### Changes
            - Added Terraform configuration files
            - Generated infrastructure recommendations
            - Created deployment documentation
            
            ### Next Steps
            1. Review the generated Terraform files
            2. Update variables in `terraform.tfvars` as needed
            3. Run `terraform plan` to verify the configuration
          branch: "inframate/terraform-files"
          base: ${{ github.event.inputs.target_branch }}
          delete-branch: true 