name: Inframate Pipeline

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Target repository to analyze (format: owner/repo)'
        required: true
        type: string
      target_branch:
        description: 'Target branch to analyze'
        required: false
        type: string
        default: 'main'

jobs:
  inframate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Pipeline Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Clone Target Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.target_repo }}
        ref: ${{ github.event.inputs.target_branch }}
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        path: target_repo

    - name: Run Inframate
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        cd target_repo
        python ../inframate_flow.py .

    - name: Configure Git
      run: |
        cd target_repo
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Create Pull Request in Target Repository
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: ${{ github.event.inputs.target_repo }}
        commit-message: "Inframate: Update infrastructure configuration"
        title: "Inframate: Infrastructure Configuration Update"
        body: |
          This PR contains infrastructure configuration updates generated by Inframate.
          
          Changes include:
          - Updated Terraform files
          - Infrastructure recommendations
          - Deployment configurations
        branch: "inframate/update-infrastructure"
        base: ${{ github.event.inputs.target_branch }} 